# Generated by Django 5.2.15 on 2026-07-16 06:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0004_groupblock_pickup_location_groupblock_pickup_target'),
        ('crm', '0002_guestcontact_crm_guestco_tenant__503a6d_idx_and_more'),
        ('reference', '0003_state'),
        ('reservations', '0006_reservation_corporate_billing_type_and_more'),
        ('tenants', '0010_alter_property_google_map_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reservation',
            name='reservation_tenant__c4d46b_idx',
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['tenant', 'status'], name='reservation_tenant__095897_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['property', 'arrival_date'], name='reservation_propert_ed2f96_idx'),
        ),
    ]
