# Generated by Django 5.2.15 on 2026-07-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_remove_reservation_reservation_tenant__c4d46b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='event_catering_menu',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='event_end_time',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='event_organizer_billing_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='event_organizer_contact',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='event_organizer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='event_organizer_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='event_pax',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='event_seating_arrangement',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='event_start_time',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='event_type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='event_venue',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
