# Generated by Django 5.2.15 on 2026-07-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_reservation_event_catering_menu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='check_in_time',
            field=models.CharField(blank=True, default='12:00 PM', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='check_out_time',
            field=models.CharField(blank=True, default='11:00 AM', max_length=32, null=True),
        ),
    ]
