# Generated by Django 5.2.15 on 2026-09-07 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_amenity_chargeable_amenity_description_and_more'),
        ('reservations', '0010_reservationextracharge'),
        ('tenants', '0013_property_booking_engine_settings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reservationinventory',
            name='checkout_after_checkin_check',
        ),
        migrations.AddConstraint(
            model_name='reservationinventory',
            constraint=models.CheckConstraint(condition=models.Q(('check_out_date__gte', models.F('check_in_date'))), name='checkout_after_checkin_check'),
        ),
    ]
