# Generated by Django 5.2.15 on 2026-07-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0004_groupblock_pickup_location_groupblock_pickup_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupblock',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='groupblock',
            name='id_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='groupblock',
            name='id_type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='groupblock',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='groupblock',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='groupblock',
            name='payment_remark',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
