# Generated by Django 5.2.15 on 2026-08-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0005_groupblock_address_groupblock_id_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupblock',
            name='extra_charges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='groupblock',
            name='meal_plan',
            field=models.CharField(blank=True, default='AP Plan', max_length=64),
        ),
        migrations.AddField(
            model_name='groupblock',
            name='meal_plan_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='groupblock',
            name='payment_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
