# Generated by Django 5.2.15 on 2026-08-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0006_groupblock_extra_charges_groupblock_meal_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupblock',
            name='nationality',
            field=models.CharField(blank=True, default='Indian', max_length=64),
        ),
    ]
