# Generated by Django 5.2.15 on 2026-08-25 07:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_property_hotel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='business_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
