# Generated by Django 6.0.6 on 2026-08-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_property_business_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='booking_engine_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='property',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
