# Generated by Django 5.2.15 on 2026-08-25 07:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_office', '0002_foliotransaction_front_offic_tenant__1428e1_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nightauditsession',
            name='cashier_closing_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='nightauditsession',
            name='cashier_opening_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='nightauditsession',
            name='cashier_variance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='nightauditsession',
            name='city_ledger_closing',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='nightauditsession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nightauditsession',
            name='deposit_ledger_closing',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='nightauditsession',
            name='guest_ledger_closing',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='nightauditsession',
            name='no_show_revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='nightauditsession',
            name='no_shows_processed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nightauditsession',
            name='occupancy_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='nightauditsession',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_night_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nightauditsession',
            name='post_audit_summary',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='nightauditsession',
            name='pre_audit_checklist_results',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='nightauditsession',
            name='rooms_occupied',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nightauditsession',
            name='rooms_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nightauditsession',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='nightauditsession',
            name='total_charges_posted',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='nightauditsession',
            name='total_packages_posted',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='nightauditsession',
            name='total_payments_received',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='nightauditsession',
            name='exception_logs',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='nightauditsession',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('ROLLED_BACK', 'Rolled Back')], default='PENDING', max_length=32),
        ),
    ]
