# Generated by Django 6.0.7 on 2026-07-21 05:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linen', '0001_initial'),
        ('reservations', '0006_banquetbooking'),
        ('tenants', '0010_alter_property_google_map_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='linenitem',
            name='damaged_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='linenitem',
            name='in_use_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='linenitem',
            name='in_wash_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='linenitem',
            name='location',
            field=models.CharField(default='Housekeeping', max_length=120),
        ),
        migrations.CreateModel(
            name='GuestLaundryOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('room_number', models.CharField(max_length=32)),
                ('guest_name', models.CharField(max_length=120)),
                ('order_number', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('expected_pickup_time', models.DateTimeField(blank=True, null=True)),
                ('service_speed', models.CharField(choices=[('STANDARD', 'Standard'), ('EXPRESS', 'Express')], default='STANDARD', max_length=16)),
                ('status', models.CharField(choices=[('PICKUP_REQUESTED', 'Pickup Requested'), ('RECEIVED_AT_LAUNDRY', 'Received at Laundry'), ('WASHING', 'Washing'), ('READY_FOR_DELIVERY', 'Ready for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PICKUP_REQUESTED', max_length=32)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_posted_to_folio', models.BooleanField(default=False)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_laundry_orders', to='tenants.property')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laundry_orders', to='reservations.reservation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_laundry_orders', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'guest_laundry_order',
            },
        ),
        migrations.CreateModel(
            name='GuestLaundryOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(default='Garment', max_length=64)),
                ('item_name', models.CharField(max_length=120)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('service', models.CharField(default='Wash & Fold', max_length=64)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='linen.guestlaundryorder')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'guest_laundry_order_item',
            },
        ),
        migrations.CreateModel(
            name='LaundryMachine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('machine_type', models.CharField(choices=[('WASHER', 'Washer'), ('DRYER', 'Dryer'), ('IRON_PRESS', 'Iron Press')], default='WASHER', max_length=32)),
                ('capacity_kg', models.CharField(default='50kg', max_length=32)),
                ('status', models.CharField(choices=[('OPERATING', 'Operating'), ('IDLE', 'Idle'), ('MAINTENANCE', 'Maintenance')], default='IDLE', max_length=32)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laundry_machines', to='tenants.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laundry_machines', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'laundry_machine',
            },
        ),
    ]
