# Generated by Django 5.2.15 on 2026-08-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrate',
            name='calculation_base',
            field=models.CharField(default='folio_subtotal', max_length=32),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='flat_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='inclusive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='max_tariff',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='min_tariff',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='type',
            field=models.CharField(default='gst', max_length=32),
        ),
        migrations.AlterField(
            model_name='billingadjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('DISCOUNT', 'Discount Adjustment'), ('REFUND', 'Refund Posting'), ('REVERSAL', 'Charge Reversal'), ('TRANSFER', 'Folio Transfer'), ('SPLIT', 'Folio Split')], max_length=32),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='code',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
