# Generated by Django 5.2.15 on 2026-08-04 10:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_appuser_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperadminIPWhitelist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=45)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superadmin_ip_whitelists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'superadmin_ip_whitelist',
                'ordering': ['-created_at'],
            },
        ),
    ]
