# Generated by Django 5.2.15 on 2026-08-29 10:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_systemmetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('method', models.CharField(db_index=True, max_length=10)),
                ('path', models.CharField(db_index=True, max_length=512)),
                ('status_code', models.IntegerField(db_index=True)),
                ('duration_ms', models.FloatField(default=0.0, help_text='Total execution latency in milliseconds')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('property_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('user_email', models.CharField(blank=True, max_length=255, null=True)),
                ('user_role', models.CharField(blank=True, max_length=64, null=True)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('query_params', models.JSONField(blank=True, null=True)),
                ('request_body', models.JSONField(blank=True, null=True)),
                ('response_summary', models.JSONField(blank=True, null=True)),
                ('headers', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'application_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'status_code'], name='application_timesta_7bd4ac_idx'), models.Index(fields=['tenant_id', '-timestamp'], name='application_tenant__f7ee6c_idx'), models.Index(fields=['method', 'path'], name='application_method_8a6e88_idx')],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('error_type', models.CharField(db_index=True, max_length=255)),
                ('error_message', models.TextField()),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=10, null=True)),
                ('path', models.CharField(blank=True, db_index=True, max_length=512, null=True)),
                ('status_code', models.IntegerField(db_index=True, default=500)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('property_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('user_id', models.CharField(blank=True, max_length=120, null=True)),
                ('user_email', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('context_data', models.JSONField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'db_table': 'error_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'error_type'], name='error_log_timesta_4ecb22_idx'), models.Index(fields=['status_code', '-timestamp'], name='error_log_status__f27830_idx'), models.Index(fields=['is_resolved', '-timestamp'], name='error_log_is_reso_c3771f_idx')],
            },
        ),
    ]
