# Generated by Django 5.2.15 on 2026-07-21 11:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_bookingsource'),
        ('tenants', '0010_alter_property_google_map_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('badge', models.CharField(blank=True, default='SECURE', max_length=64)),
                ('logo_url', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_payment_gateways',
            },
        ),
        migrations.CreateModel(
            name='TenantPaymentGateway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('api_key', models.CharField(blank=True, default='', max_length=255)),
                ('api_secret', models.CharField(blank=True, default='', max_length=255)),
                ('merchant_id', models.CharField(blank=True, default='', max_length=255)),
                ('extra_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_configs', to='common.paymentgateway')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_payment_gateways', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_payment_gateways',
                'unique_together': {('tenant', 'gateway')},
            },
        ),
    ]
