# Generated by Django 5.2.15 on 2026-08-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_paymentgateway_tenantpaymentgateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemtax',
            name='calculation_base',
            field=models.CharField(default='folio_subtotal', max_length=32),
        ),
        migrations.AddField(
            model_name='systemtax',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='systemtax',
            name='flat_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='systemtax',
            name='inclusive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemtax',
            name='max_tariff',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='systemtax',
            name='min_tariff',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='systemtax',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
