# Generated by Django 5.2.15 on 2026-08-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_systemtax_calculation_base_systemtax_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingsource',
            name='icon',
            field=models.TextField(blank=True, default=''),
        ),
    ]
