# Generated by Django 6.0.7 on 2026-07-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostfounditem',
            name='finder_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='lostfounditem',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='lost_found/'),
        ),
        migrations.AddField(
            model_name='lostfounditem',
            name='reference_number',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lostfounditem',
            name='status',
            field=models.CharField(choices=[('REPORTED', 'Reported'), ('MATCHED', 'Matched'), ('AWAITING_CLAIM', 'Awaiting Claim'), ('CLAIMED', 'Claimed'), ('DISPOSED', 'Disposed')], default='REPORTED', max_length=32),
        ),
    ]
