# Generated by Django 6.0.6 on 2026-07-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='facebook_url',
            field=models.URLField(blank=True, default='https://facebook.com/retrod', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='instagram_url',
            field=models.URLField(blank=True, default='https://instagram.com/retrod', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='linkedin_url',
            field=models.URLField(blank=True, default='https://linkedin.com/company/retrod', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='twitter_url',
            field=models.URLField(blank=True, default='https://twitter.com/retrod', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='youtube_url',
            field=models.URLField(blank=True, default='https://youtube.com/@retrod', max_length=255, null=True),
        ),
    ]
