# Generated by Django 6.0.6 on 2026-07-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_guest_company_contact_guest_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
