# Generated by Django 6.0.6 on 2026-08-01 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_roomtype_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='chain_name',
            field=models.CharField(default='Retrod Hotels', max_length=150),
        ),
        migrations.AddField(
            model_name='hotel',
            name='property_type',
            field=models.CharField(default='Hotel', max_length=50),
        ),
        migrations.AddField(
            model_name='hotel',
            name='star_rating',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='roominventory',
            name='closed_to_arrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roominventory',
            name='closed_to_departure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roominventory',
            name='max_los',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='roominventory',
            name='min_los',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Percentage'), ('FLAT', 'Flat Amount')], default='PERCENT', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_booking_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('max_redemptions', models.IntegerField(default=100)),
                ('times_redeemed', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_corporate', models.BooleanField(default=False)),
                ('corporate_company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='booking.hotel')),
            ],
        ),
    ]
