# Generated by Django 6.0.6 on 2026-08-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_hotel_chain_name_hotel_property_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
