# Generated by Django 6.0.6 on 2026-08-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_roomtype_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='corporate_company_name',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='description',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='is_corporate',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='max_discount_amount',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='max_redemptions',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='min_booking_amount',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='times_redeemed',
        ),
        migrations.AddField(
            model_name='promocode',
            name='min_nights',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_type',
            field=models.CharField(default='percentage', max_length=20),
        ),
    ]
