# Generated by Django 6.0.6 on 2026-08-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_promocode_corporate_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateplan',
            name='extra_adult_price',
            field=models.DecimalField(decimal_places=2, default=700.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rateplan',
            name='extra_child_price',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
    ]
