# Generated by Django 6.0.6 on 2026-08-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_rateplan_extra_adult_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='base_included_adults',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='base_included_children',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='max_adults',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='max_children',
            field=models.IntegerField(default=2),
        ),
    ]
