# Generated by Django 6.0.6 on 2026-08-10 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_roomtype_base_included_adults_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='booking_engine_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='hotel',
            name='page_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='theme_color',
            field=models.CharField(default='#ffc107', max_length=50),
        ),
        migrations.CreateModel(
            name='AddonPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(default='Dining', max_length=50)),
                ('charge_type', models.CharField(default='Per Stay', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_pct', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='booking.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100)),
                ('key_id', models.CharField(blank=True, max_length=255, null=True)),
                ('key_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('sandbox', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('pay_at_hotel', models.BooleanField(default=False)),
                ('deposit_pct', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_gateways', to='booking.hotel')),
            ],
        ),
    ]
