# Generated by Django 6.0.6 on 2026-08-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_hotel_booking_engine_settings_hotel_page_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='backstory',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='what_makes_special',
            field=models.TextField(blank=True, null=True),
        ),
    ]
