# Generated by Django 6.1 on 2026-08-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_hotel_backstory_hotel_what_makes_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='enable_google_reviews',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='google_reviews_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='hotel',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
