# Generated by Django 6.0.6 on 2026-08-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_hotel_enable_google_reviews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='room_images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
