# Generated by Django 6.0.6 on 2026-08-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_roomtype_room_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='addons_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_addons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='catering_plan',
            field=models.CharField(blank=True, default='Standard Buffet', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='halls_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='total_addons_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='total_catering_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
