# Generated by Django 6.0.6 on 2026-08-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_booking_addons_total_booking_selected_addons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='policy',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='bed_type',
            field=models.CharField(default='King', max_length=255),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
