# Generated by Django 6.0.7 on 2026-07-18 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_amenity_chargeable_amenity_description_and_more'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceticket',
            name='category',
            field=models.CharField(choices=[('HVAC', 'HVAC'), ('PLUMBING', 'Plumbing'), ('ELECTRICAL', 'Electrical'), ('FURNITURE', 'Furniture'), ('GENERAL', 'General')], default='GENERAL', max_length=32),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='reference_number',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='inventory_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tickets', to='inventory.inventoryunit'),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='priority',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=16),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='status',
            field=models.CharField(choices=[('REPORTED', 'Reported'), ('IN_PROGRESS', 'In Progress'), ('WAITING_PARTS', 'Waiting Parts'), ('RESOLVED', 'Resolved')], default='REPORTED', max_length=32),
        ),
    ]
