# Generated by Django 6.0.7 on 2026-07-15 06:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0010_alter_property_google_map_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BPartner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('agent_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending KYC', 'Pending KYC'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending KYC', max_length=32)),
                ('commission_rate', models.IntegerField(default=0)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('incorporation_document', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_id_document', models.CharField(blank=True, max_length=255, null=True)),
                ('cheque_document', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_partners', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'B2B Partner',
                'verbose_name_plural': 'B2B Partners',
                'db_table': 'b2b_partners',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'agent_id'), name='unique_tenant_b2b_agent_id')],
            },
        ),
    ]
