# Generated by Django 6.0.7 on 2026-07-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2bpartner',
            name='cheque_document',
            field=models.FileField(blank=True, null=True, upload_to='b2b_documents/'),
        ),
        migrations.AlterField(
            model_name='b2bpartner',
            name='incorporation_document',
            field=models.FileField(blank=True, null=True, upload_to='b2b_documents/'),
        ),
        migrations.AlterField(
            model_name='b2bpartner',
            name='owner_id_document',
            field=models.FileField(blank=True, null=True, upload_to='b2b_documents/'),
        ),
    ]
