# Generated by Django 5.2.15 on 2026-07-29 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currencies', to='reference.country'),
        ),
    ]
