# Generated by Django 5.2.15 on 2026-08-10 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0007_servicecategory_alter_service_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateplaninventorytype',
            name='extra_adult_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='rateplaninventorytype',
            name='extra_child_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='rateplaninventorytype',
            name='guest_rates',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='rateplaninventorytype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rateplan',
            name='cancellation_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rate_plans', to='rates.cancellationpolicy'),
        ),
        migrations.AlterField(
            model_name='rateplan',
            name='child_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rate_plans', to='rates.childpolicy'),
        ),
    ]
