# Generated by Django 5.2.15 on 2026-08-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0008_rateplaninventorytype_extra_adult_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateplan',
            name='meal_plans',
            field=models.ManyToManyField(blank=True, related_name='included_rate_plans', to='rates.mealplan'),
        ),
    ]
